openapi: 3.0.2
info:
  title: Wallet-Pay API Documentations
  version: "1.0"
servers:
- url: https://api.wallet-pay.openweb3.io
security:
- ApiKeyAuth: []
paths:
  /api/v1/currencies:
    get:
      description: List currencies.
      operationId: v1.currency.list
      parameters:
      - description: Specified the app id.
        explode: true
        in: query
        name: app_id
        required: false
        schema:
          description: Specified the app id.
          example: app_12345xsfei
          type: string
        style: form
      - description: Limit the number of returned items
        explode: true
        in: query
        name: size
        required: false
        schema:
          default: 20
          description: Limit the number of returned items
          example: 100
          format: uint64
          minimum: 0
          type: integer
        style: form
      - description: Specifying the page index
        explode: true
        in: query
        name: page
        required: false
        schema:
          default: 0
          description: Specifying the page index
          example: 0
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListResponse_CurrencyOut_'
          description: OK
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
          description: Forbidden
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
          description: Not Found
        "409":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
          description: Conflict
        "429":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
          description: Too Many Requests
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
          description: Internal Server Error
      summary: List currencies
      tags:
      - Currency
      x-accepts: application/json
  /api/v1/apps/currencies/{code}:
    get:
      description: Get specified currency.
      operationId: v1.currency.findByCode
      parameters:
      - description: Specified currency code.
        explode: false
        in: path
        name: code
        required: true
        schema:
          description: Specified currency code.
          example: USDT
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseCurrencyOut'
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseCurrencyOut'
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
          description: Forbidden
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
          description: Not Found
        "409":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
          description: Conflict
        "429":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
          description: Too Many Requests
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
          description: Internal Server Error
      summary: Find currency by code
      tags:
      - Currency
      x-accepts: application/json
  /api/v1/apps/{appId}/orders:
    get:
      description: List orders.
      operationId: v1.order.list
      parameters:
      - description: Specified the app id.
        explode: false
        in: path
        name: appId
        required: true
        schema:
          description: Specified the app id.
          example: app_12345xsfei
          type: string
        style: simple
      - description: Limit the number of returned items
        explode: true
        in: query
        name: size
        required: false
        schema:
          default: 20
          description: Limit the number of returned items
          example: 100
          format: uint64
          minimum: 0
          type: integer
        style: form
      - description: Specifying the page index
        explode: true
        in: query
        name: page
        required: false
        schema:
          default: 0
          description: Specifying the page index
          example: 0
          type: integer
        style: form
      - description: Optional wallet id
        explode: true
        in: query
        name: wallet_id
        required: false
        schema:
          description: Optional wallet id
          example: wallet_id
          nullable: true
          type: string
        style: form
      - description: Optional account id
        explode: true
        in: query
        name: account_id
        required: false
        schema:
          description: Optional account id
          example: account_id
          nullable: true
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListResponse_OrderOut_'
          description: OK
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
          description: Forbidden
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
          description: Not Found
        "409":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
          description: Conflict
        "429":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
          description: Too Many Requests
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
          description: Internal Server Error
      summary: List Orders
      tags:
      - Order
      x-accepts: application/json
    post:
      description: Create a new order.
      operationId: v1.order.create
      parameters:
      - description: Specified the app id.
        explode: false
        in: path
        name: appId
        required: true
        schema:
          description: Specified the app id.
          example: app_12345xsfei
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderIn'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderOut'
          description: OK
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderOut'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
          description: Bad request
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
          description: Forbidden
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
          description: Not Found
        "409":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
          description: Conflict
        "429":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
          description: Too Many Requests
      summary: Create Order
      tags:
      - Order
      x-readme:
        code-samples: []
      x-contentType: application/json
      x-accepts: application/json
  /api/v1/apps/{appId}/orders/{idOrUid}:
    get:
      description: Get specified order.
      operationId: v1.order.get
      parameters:
      - description: Specified the app id.
        explode: false
        in: path
        name: appId
        required: true
        schema:
          description: Specified the app id.
          example: app_12345xsfei
          type: string
        style: simple
      - description: Specified the order id or order uid.
        explode: false
        in: path
        name: idOrUid
        required: true
        schema:
          description: Specified the order id or order uid.
          example: 11b9ca57-0559-403a-bf8e-7bd1a31aff45
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseOrderOut'
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseOrderOut'
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
          description: Forbidden
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
          description: Not Found
        "409":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
          description: Conflict
        "429":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
          description: Too Many Requests
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
          description: Internal Server Error
      summary: Get order
      tags:
      - Order
      x-accepts: application/json
  /api/v1/webhooks/endpoints:
    get:
      description: List endpoints.
      operationId: v1.endpoint.list
      parameters:
      - description: Limit the number of returned items
        explode: true
        in: query
        name: limit
        required: false
        schema:
          default: 20
          description: Limit the number of returned items
          example: 100
          format: uint64
          minimum: 0
          type: integer
        style: form
      - description: Specifying the start cursor position
        explode: true
        in: query
        name: cursor
        required: false
        schema:
          description: Specifying the start cursor position
          type: string
        style: form
      - description: The sorting order of the returned items
        explode: true
        in: query
        name: ordering
        required: false
        schema:
          $ref: '#/components/schemas/Ordering'
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListResponse_EndpointOut_'
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
          description: Forbidden
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
          description: Not Found
        "409":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
          description: Conflict
        "429":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
          description: Too Many Requests
      summary: List endpoints
      tags:
      - Webhook Endpoint
      x-accepts: application/json
    post:
      description: Create a webhook endpoint.
      operationId: v1.endpoint.create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EndpointIn'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseEndpointOut'
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseEndpointOut'
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
          description: Bad request
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
          description: Forbidden
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
          description: Not Found
        "409":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
          description: Conflict
        "429":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
          description: Too Many Requests
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
          description: Internal Server Error
      summary: Create endpoint
      tags:
      - Webhook Endpoint
      x-readme:
        code-samples: []
      x-contentType: application/json
      x-accepts: application/json
  /api/v1/webhooks/endpoints/{endpointId}:
    delete:
      description: delete the specified webhook endpoint.
      operationId: v1.endpoint.delete
      parameters:
      - description: Specified the endpoint id.
        explode: false
        in: path
        name: endpointId
        required: true
        schema:
          description: Specified the endpoint id.
          example: wb_12345xsfei
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseEndpointOut'
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseEndpointOut'
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
          description: Forbidden
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
          description: Not Found
        "409":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
          description: Conflict
        "429":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
          description: Too Many Requests
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
          description: Internal Server Error
      summary: Delete endpoint
      tags:
      - Webhook Endpoint
      x-accepts: application/json
    get:
      description: get the specified webhook endpoint.
      operationId: v1.endpoint.get
      parameters:
      - description: Specified the endpoint id or endpoint uid.
        explode: false
        in: path
        name: endpointId
        required: true
        schema:
          description: Specified the endpoint id.
          example: wb_12345xsfei
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseEndpointOut'
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseEndpointOut'
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
          description: Forbidden
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
          description: Not Found
        "409":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
          description: Conflict
        "429":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
          description: Too Many Requests
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
          description: Internal Server Error
      summary: Delete endpoint
      tags:
      - Webhook Endpoint
      x-accepts: application/json
components:
  schemas:
    ResponseError:
      properties:
        msg:
          type: string
        code:
          type: integer
      required:
      - code
      - msg
      title: ResponseError
      type: object
    Ordering:
      description: Defines the ordering in a listing of results.
      enum:
      - asc
      - desc
      type: string
    WebhookMessage:
      description: The request body of the webhook POST request.
      properties:
        event_type:
          description: Message event type
          example: order_paid
          maxLength: 256
          minLength: 1
          type: string
        payload:
          $ref: '#/components/schemas/OrderOut'
    ResponseCurrencyOut:
      example:
        data:
          max_withdraw_amount: "0.0012345"
          symbol: http://symbol.jpg
          code: USDT
          precision: 6
          decimals: 12
          name: http://logo.jpg
          logo: http://logo.jpg
          can_withdraw: false
          can_deposit: false
          can_transfer: false
          min_deposit_amount: "0.0012345"
          min_withdraw_amount: "0.0012345"
      properties:
        data:
          $ref: '#/components/schemas/CurrencyOut'
      required:
      - data
      title: ResponseCurrencyOut
      type: object
    CurrencyOut:
      example:
        max_withdraw_amount: "0.0012345"
        symbol: http://symbol.jpg
        code: USDT
        precision: 6
        decimals: 12
        name: http://logo.jpg
        logo: http://logo.jpg
        can_withdraw: false
        can_deposit: false
        can_transfer: false
        min_deposit_amount: "0.0012345"
        min_withdraw_amount: "0.0012345"
      properties:
        code:
          description: Currency code
          example: USDT
          maxLength: 256
          minLength: 1
          type: string
        symbol:
          description: Currency symbol
          example: http://symbol.jpg
          maxLength: 256
          minLength: 1
          type: string
        logo:
          description: Currency logo url
          example: http://logo.jpg
          maxLength: 256
          minLength: 1
          type: string
        name:
          description: Currency name
          example: http://logo.jpg
          maxLength: 256
          minLength: 1
          type: string
        can_deposit:
          description: Is it posible to deposit on blockchain
          example: false
          type: boolean
        can_withdraw:
          description: Is it posible to withdraw to blockchain
          example: false
          type: boolean
        can_transfer:
          description: Is it posible to transfer in custody wallet
          example: false
          type: boolean
        min_deposit_amount:
          description: Big decimal string representation. The min amount to deposit.
          example: "0.0012345"
          maxLength: 256
          minLength: 1
          type: string
        min_withdraw_amount:
          description: Big decimal string representation. The min amount to withdraw.
          example: "0.0012345"
          maxLength: 256
          minLength: 1
          type: string
        max_withdraw_amount:
          description: Big decimal string representation. The max amount to withdraw.
          example: "0.0012345"
          maxLength: 256
          minLength: 1
          type: string
        precision:
          description: Currency precision
          example: 6
          type: integer
        decimals:
          description: Currency decimal
          example: 12
          type: integer
      required:
      - can_deposit
      - can_transfer
      - can_withdraw
      - code
      - decimals
      - logo
      - max_withdraw_amount
      - min_deposit_amount
      - min_withdraw_amount
      - name
      - precision
      - symbol
      type: object
    ListResponse_CurrencyOut_:
      example:
        total: 0
        items:
        - max_withdraw_amount: "0.0012345"
          symbol: http://symbol.jpg
          code: USDT
          precision: 6
          decimals: 12
          name: http://logo.jpg
          logo: http://logo.jpg
          can_withdraw: false
          can_deposit: false
          can_transfer: false
          min_deposit_amount: "0.0012345"
          min_withdraw_amount: "0.0012345"
        - max_withdraw_amount: "0.0012345"
          symbol: http://symbol.jpg
          code: USDT
          precision: 6
          decimals: 12
          name: http://logo.jpg
          logo: http://logo.jpg
          can_withdraw: false
          can_deposit: false
          can_transfer: false
          min_deposit_amount: "0.0012345"
          min_withdraw_amount: "0.0012345"
      properties:
        items:
          items:
            $ref: '#/components/schemas/CurrencyOut'
          type: array
        total:
          type: integer
      required:
      - items
      type: object
    OrderIn:
      example:
        uid: unique-order-identifier
        note: note example
        amount: "0.0012345"
        metadata:
          key: metadata
        currency: USDT
        expiration: 600
      properties:
        uid:
          description: Optional unique identifier for the order
          example: unique-order-identifier
          maxLength: 256
          minLength: 1
          nullable: true
          pattern: ^[a-zA-Z0-9\-_.]+$
          type: string
        currency:
          description: Currency code
          example: USDT
          maxLength: 256
          minLength: 1
          type: string
        amount:
          description: Big decimal string representation. Note that the max precision
            (number of digits after decimal point) depends on the currencyCode. E.g.
            for all fiat currencies is 2 (0.01), for BTC is 8, for USDT is 6. There's
            also min order amount for creating an order. It's 0.000001 BTC / 0.01
            USDT / 0.01 USD / 0.01 EUR / 0.1 RUB.
          example: "0.0012345"
          maxLength: 256
          minLength: 1
          type: string
        note:
          description: Optional order note
          example: note example
          maxLength: 256
          minLength: 1
          type: string
        metadata:
          additionalProperties:
            type: string
          default: {}
          description: Optional metadata
          nullable: true
          type: object
        expiration:
          description: The expiration seconds
          example: 600
          type: integer
      required:
      - amount
      - currency
      type: object
    OrderOut:
      example:
        note: note example
        amount: "1"
        metadata:
          key: metadata
        created_at: 2000-01-23T04:56:07.000+00:00
        expired_at: 2000-01-23T04:56:07.000+00:00
        failed_message: failed_message
        uid: unique-order-identifier
        wallet_id: wallet_id
        payed_at: 2000-01-23T04:56:07.000+00:00
        user_id: user_id
        currency: USDT
        expiration: 600
        id: 1brOrx2ZWZBpBUvZwXKQmoEYga2
        failed_at: 2000-01-23T04:56:07.000+00:00
        status: PENDING
      properties:
        id:
          description: The order's ID
          example: 1brOrx2ZWZBpBUvZwXKQmoEYga2
          type: string
        uid:
          description: The order's UID
          example: unique-order-identifier
          maxLength: 256
          minLength: 1
          nullable: true
          pattern: ^[a-zA-Z0-9\-_.]+$
          type: string
        currency:
          description: Currency code
          example: USDT
          maxLength: 256
          minLength: 1
          type: string
        amount:
          description: Big decimal string representation. Note that the max precision
            (number of digits after decimal point) depends on the currencyCode. E.g.
            for all fiat currencies is 2 (0.01), for BTC is 8, for USDT is 6. There's
            also min order amount for creating an order. It's 0.000001 BTC / 0.01
            USDT / 0.01 USD / 0.01 EUR / 0.1 RUB.
          example: "1"
          maxLength: 256
          minLength: 1
          type: string
        user_id:
          description: The order's creator
          nullable: true
          type: string
        wallet_id:
          description: wallet id
          example: wallet_id
          maxLength: 256
          minLength: 1
          type: string
        note:
          description: Optional order notes
          example: note example
          maxLength: 256
          minLength: 1
          type: string
        metadata:
          additionalProperties:
            type: string
          type: object
        expiration:
          description: The expiration seconds
          example: 600
          type: integer
        status:
          description: The order's status
          enum:
          - PENDING
          - PAID
          - FAILED
          - EXPIRED
          - COMPLETED
          type: string
        failed_message:
          description: The message when order failed
          type: string
        created_at:
          description: The order's creation time
          format: date-time
          type: string
        payed_at:
          description: The order's paid time
          format: date-time
          type: string
        expired_at:
          description: The order's expiration time
          format: date-time
          type: string
        failed_at:
          description: The order's failure time
          format: date-time
          type: string
      required:
      - amount
      - created_at
      - currency
      - id
      - status
      type: object
    ListResponse_OrderOut_:
      example:
        total: 0
        items:
        - note: note example
          amount: "1"
          metadata:
            key: metadata
          created_at: 2000-01-23T04:56:07.000+00:00
          expired_at: 2000-01-23T04:56:07.000+00:00
          failed_message: failed_message
          uid: unique-order-identifier
          wallet_id: wallet_id
          payed_at: 2000-01-23T04:56:07.000+00:00
          user_id: user_id
          currency: USDT
          expiration: 600
          id: 1brOrx2ZWZBpBUvZwXKQmoEYga2
          failed_at: 2000-01-23T04:56:07.000+00:00
          status: PENDING
        - note: note example
          amount: "1"
          metadata:
            key: metadata
          created_at: 2000-01-23T04:56:07.000+00:00
          expired_at: 2000-01-23T04:56:07.000+00:00
          failed_message: failed_message
          uid: unique-order-identifier
          wallet_id: wallet_id
          payed_at: 2000-01-23T04:56:07.000+00:00
          user_id: user_id
          currency: USDT
          expiration: 600
          id: 1brOrx2ZWZBpBUvZwXKQmoEYga2
          failed_at: 2000-01-23T04:56:07.000+00:00
          status: PENDING
      properties:
        items:
          items:
            $ref: '#/components/schemas/OrderOut'
          type: array
        total:
          type: integer
      required:
      - items
      type: object
    ResponseOrderOut:
      example:
        data:
          note: note example
          amount: "1"
          metadata:
            key: metadata
          created_at: 2000-01-23T04:56:07.000+00:00
          expired_at: 2000-01-23T04:56:07.000+00:00
          failed_message: failed_message
          uid: unique-order-identifier
          wallet_id: wallet_id
          payed_at: 2000-01-23T04:56:07.000+00:00
          user_id: user_id
          currency: USDT
          expiration: 600
          id: 1brOrx2ZWZBpBUvZwXKQmoEYga2
          failed_at: 2000-01-23T04:56:07.000+00:00
          status: PENDING
      properties:
        data:
          $ref: '#/components/schemas/OrderOut'
      required:
      - data
      title: ResponseOrderOut
      type: object
    EndpointIn:
      example:
        uid: unique-endpoint-identifier
        headers:
          x-user-id: user1
          x-org-id: org_xdwfeees1xfeg
        metadata:
          node: http://dashboard.com/node1
          tag: node
        description: The description for endpoint
        filter_types:
        - tx.created
        disabled: false
        url: http://example.com/endpoint
      properties:
        uid:
          description: Optional unique identifier for the endpoint
          example: unique-endpoint-identifier
          maxLength: 256
          minLength: 1
          nullable: true
          pattern: ^[a-zA-Z0-9\-_.]+$
          type: string
        filter_types:
          description: The webhook endpoint expected event types
          example:
          - tx.created
          items:
            type: string
          type: array
        url:
          description: The webhook endpoint url
          example: http://example.com/endpoint
          type: string
        disabled:
          description: indicate whether to disable the webhook endpoint
          example: false
          type: boolean
        metadata:
          additionalProperties:
            type: string
          default: {}
          description: Optional metadata
          example:
            node: http://dashboard.com/node1
            tag: node
          nullable: true
          type: object
        headers:
          additionalProperties:
            type: string
          default: {}
          description: Optional headers
          example:
            x-user-id: user1
            x-org-id: org_xdwfeees1xfeg
          nullable: true
          type: object
        description:
          description: The endpoint's description
          example: The description for endpoint
          type: string
      required:
      - filter_types
      - url
      type: object
    EndpointOut:
      example:
        headers:
          x-user-id: user1
          x-org-id: org_xdwfeees1xfeg
        metadata:
          node: http://dashboard.com/node1
          tag: node
        description: The description for endpoint
        filter_types:
        - tx.created
        disabled: false
        url: http://example.com/endpoint
      properties:
        description:
          description: The endpoint's description
          example: The description for endpoint
          type: string
        url:
          description: The webhook endpoint url
          example: http://example.com/endpoint
          type: string
        filter_types:
          description: The webhook endpoint expected event types
          example:
          - tx.created
          items:
            type: string
          type: array
        disabled:
          description: indicate whether to disable the webhook endpoint
          example: false
          type: boolean
        metadata:
          additionalProperties:
            type: string
          default: {}
          description: Optional metadata
          example:
            node: http://dashboard.com/node1
            tag: node
          type: object
        headers:
          additionalProperties:
            type: string
          default: {}
          description: Optional headers
          example:
            x-user-id: user1
            x-org-id: org_xdwfeees1xfeg
          type: object
      required:
      - filter_types
      - url
      type: object
    ListResponse_EndpointOut_:
      example:
        prev_cursor: prev_cursor
        next_cursor: next_cursor
        items:
        - headers:
            x-user-id: user1
            x-org-id: org_xdwfeees1xfeg
          metadata:
            node: http://dashboard.com/node1
            tag: node
          description: The description for endpoint
          filter_types:
          - tx.created
          disabled: false
          url: http://example.com/endpoint
        - headers:
            x-user-id: user1
            x-org-id: org_xdwfeees1xfeg
          metadata:
            node: http://dashboard.com/node1
            tag: node
          description: The description for endpoint
          filter_types:
          - tx.created
          disabled: false
          url: http://example.com/endpoint
      properties:
        items:
          items:
            $ref: '#/components/schemas/EndpointOut'
          type: array
        prev_cursor:
          type: string
        next_cursor:
          type: string
      required:
      - items
      type: object
    ResponseEndpointOut:
      example:
        data:
          headers:
            x-user-id: user1
            x-org-id: org_xdwfeees1xfeg
          metadata:
            node: http://dashboard.com/node1
            tag: node
          description: The description for endpoint
          filter_types:
          - tx.created
          disabled: false
          url: http://example.com/endpoint
      properties:
        data:
          $ref: '#/components/schemas/EndpointOut'
      required:
      - data
      title: ResponseEndpointOut
      type: object
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: x-api-key
      type: apiKey
x-readme:
  samples-languages:
  - python
  - node
  - csharp
  - java
  - go
  - kotlin
  - ruby
  - rust
  - java
  - shell
  parameter-ordering:
  - path
  - query
  - header
  - cookie
  - body
  - form

